### ISSUE TITLE
Down button not working in :Tcd

### ISSUE THREAD

**Issue by johanssondavid** [philip-karlsson/bolt.nvim#6]
> Fel upptäcktes vid bearbetning av function remote#define#CommandBootstrap[5]..remote#define#request:
> rad    2:
> error caught in request handler '/Users/david/dev/VimPlugs/bolt.nvim/rplugin/python3/vim_tc_explorer:command:TcExpDown 
> [[], [1, 1]]':
> Traceback (most recent call last):
>   File "/Users/david/dev/VimPlugs/bolt.nvim/rplugin/python3/vim_tc_explorer/__init__.py", line 35, in tc_down
>     self.TcExplorer.tc_down(args, range)
>   File "/Users/david/dev/VimPlugs/bolt.nvim/rplugin/python3/vim_tc_explorer/vim_tc_explorer.py", line 216, in tc_down
>     exp.window.cursor = (exp.selected + exp.headerLength, 0)
> AttributeError: 'explorer' object has no attribute 'window'

To reproduce
1. nvim
2. :Tcd
3. Press key Down

**Comment by johanssondavid** [comment]
The error was introduced in 8f83f70

**Comment by ripxorip** [comment]
Should be easy to fix, will give it a go.

**Comment by ripxorip** [comment]
Solved in [cd1f57b](https://github.com/philip-karlsson/bolt.nvim/commit/cd1f57bb412ef8d1b14c9c2b1065ea89e9219263)
